#
# Copyright (c) 2023 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/herdstat/.github.
#
# SPDX-License-Identifier: MIT
#

verbose: true

repositories:
  - herdstat

filters:
  commits:
    - "Author.Name == 'github-actions' && Message matches 'Update contribution graph.*'"
