#
# Copyright (c) 2023 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/herdstat/.github.
#
# SPDX-License-Identifier: MIT
#

name: Automatically label issues (incl. needs-triage)
on:
  # Allows workflow to be reusable (see https://docs.github.com/en/actions/using-workflows/reusing-workflows)
  workflow_call:
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label Issues
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "needs-triage"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
